spring.application.name=BackendAdventureApp

spring.datasource.url=jdbc:mysql://localhost:3306/jemsadventure
spring.datasource.username=root
spring.datasource.password=MySQLpasswordMySQL
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
